//
//  ProductsListViewController.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Haseeb Siddiqui
//

import UIKit

class ProductsListViewController: UIViewController {

    // User interface
    let userInterface: ProductsListInterfaceView
    let productListDataSoruceAndDelegate = ProductListDatasourceAndDelegate()

    var presenter: ProductsListPresenterProtocol?
    
    init(
        userInterface: ProductsListInterfaceView
    ) {
        self.userInterface = userInterface
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    
    override func loadView() {
        self.view = userInterface
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        presenter?.viewLoaded()
        setupAccessibilityIdentifiers()
    }
    
    func setupUI() {
        title = AppStrings.productListNavbarTitle //Fixme should be somewhere in localization file :(
        
        userInterface.setDataSourceAndDelegateForProductsTableView(productListDataSoruceAndDelegate)
    }
}

extension ProductsListViewController: ProductsListViewProtocol {
    
    func displayProductList(with viewModels: [ProductListItemViewModel]) {
        
        productListDataSoruceAndDelegate.setModels(viewModels)
        userInterface.reloadListOfProducts()
    }
    
    func displayLoader() {
        userInterface.showActivityIndicator()
    }
    
    func hideLoader() {
        userInterface.hideActivityIndicator()
    }
    
    func displayErrorMsg(_ message: String) {
        // notify view to show something
        userInterface.showError(with: message)
    }
    
}


//for UITEsting
extension ProductsListViewController {
    func setupAccessibilityIdentifiers() {
        self.navigationController?.navigationBar.accessibilityIdentifier = UIElementsIdentifiers.ProductList.navbar
    }
}
