//
//  ProductsListProtocols.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Haseeb Siddiqui
//

import Foundation

// MARK: Wireframe -
protocol ProductsListWireframeProtocol: AnyObject {
    func routeToProductDetail(with entitiy: ProductEntity) 
}
// MARK: Presenter -
protocol ProductsListPresenterProtocol: AnyObject {

    var interactor: ProductsListInteractorInputProtocol? { get set }
    var listOfProductsViewModel: [ProductListItemViewModel] { get set }

    func viewLoaded()
}

// MARK: Interactor -
protocol ProductsListInteractorOutputProtocol: AnyObject {

    /* Interactor -> Presenter */
    func presentListOfProducts(_ products: [ProductEntity])
    func presentErrorInFetchingProductsList(with error: Error)
}

protocol ProductsListInteractorInputProtocol: AnyObject {

    var presenter: ProductsListInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
    func getProductsList()
}

// MARK: View -
protocol ProductsListViewProtocol: AnyObject {

    var presenter: ProductsListPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func displayProductList(with viewModels: [ProductListItemViewModel])
    func displayErrorMsg(_ message: String)
    func displayLoader()
    func hideLoader()
}
