//
//  ProductsListRouter.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Haseeb Siddiqui
//

import UIKit

class ProductsListRouter: ProductsListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ProductsListView()
        let viewController = ProductsListViewController(userInterface: view)
        let interactor = ProductsListInteractor(productListService: ProductsListService())
        let router = ProductsListRouter()
        let presenter = ProductsListPresenter(interface: viewController, interactor: interactor, router: router)

        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController

        return viewController
    }
    
    func routeToProductDetail(with entitiy: ProductEntity) {
        self.viewController?.navigationController?.pushViewController(ProductDetailRouter.createModule(with: entitiy), animated: true)
    }
}
