//
//  ProductDetailViewController.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Hassan Asim
//

import UIKit

class ProductDetailViewController: UIViewController, ProductDetailViewProtocol {
    
    let userInterface: ProductDetailInterfaceView
    
    var presenter: ProductDetailPresenterProtocol?

    init(
        userInterface: ProductDetailInterfaceView
    ) {
        self.userInterface = userInterface
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func loadView() {
        self.view = userInterface
    }

    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.viewLoaded()
        self.title = AppStrings.productDetailsNavbarTitle
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    func displayProductDetail(with viewModel: ProductDetailViewModel) {
        userInterface.setupData(viewModel)
    }

}
