//
//  ProductDetailInteractor.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Hassan Asim
//

import UIKit

class ProductDetailInteractor: ProductDetailInteractorInputProtocol {

    weak var presenter: ProductDetailInteractorOutputProtocol?
    
    var productEntity: ProductEntity
    
    init(product: ProductEntity) {
        self.productEntity = product
    }
    
    func getProductDetails() {
        presenter?.presentProductDetails(with: self.productEntity)
    }
}
