//
//  ProductDetailRouter.swift
//  Dubizzle
//
//  Created Muhammad Haseeb Siddiqui on 4/4/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Muhammad Hassan Asim
//

import UIKit

class ProductDetailRouter: ProductDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(with product: ProductEntity) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ProductDetailViewController(userInterface: ProductDetailView())
        let interactor = ProductDetailInteractor(product: product)
        let router = ProductDetailRouter()
        let presenter = ProductDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
